<a href="https://colab.research.google.com/github/papagorgio23/Python101/blob/master/Tic_Tac_Toe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Tic-Tac-Toe
#### This code is copied/modified from:
https://www.geeksforgeeks.org/python-implementation-automatic-tic-tac-toe-game-using-random-number/

In [ ]:
# Tic-Tac-Toe Program
  
# importing all necessary libraries 
import numpy as np 
import random 
from time import sleep 

In [ ]:
# Create an empty board 
def create_board(): 
  #create a 3 x 3 array of 0's
  return(np.full((3,3),0))

In [ ]:
#Print a test board
create_board()

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
# Check for empty places on board 
def possibilities(board): 
    #Create list of openSpots
    openSpots = []
    #Iterate through rows  
    for row in range(len(board)):
        #Iterate through columns
        for col in range(len(board)):
            #Check if location is empty
            if board[row][col] == 0:
              #If empty, append to list of openSpots
              openSpots.append((row, col))
    #return openSpots
    return(openSpots) 

In [ ]:
board = create_board()
possibilities(board)

[(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)]

In [ ]:
?np.array

In [ ]:
#Show possibilities - Run possibilities function with test board
#allSpots = possibilities(board)
#print(allSpots)

#Create key for the user input for turn locations
# returns a 3x3 array with numbers 0 - 8
def boardMap():
  return(np.arange(9).reshape(3,3))


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#print out board map
print(boardMap())

In [ ]:
# Select a random place for the computer player 
def random_place(board, player):
    #Get all possibilities
    selection = possibilities(board)
    #randomly select a location out of available spots
    current_loc = random.choice(selection)
    #update board with randomly selected location for specific player
    board[current_loc] = player
    #return updated board
    return(board)

In [ ]:
board = create_board()
random_place(board, 1)
random_place(board, 2)
random_place(board, 1)
random_place(board, 2)
random_place(board, 1)
random_place(board, 2)
random_place(board, 1)
random_place(board, 2)
random_place(board, 1)

array([[2, 2, 1],
       [1, 2, 1],
       [2, 1, 1]])

In [ ]:
#Get available locations on board
#Check if players entry is valid
#If yes, update board and return board
#If no, do not update board and return none
def player_turn(board, player, location):
    #Get Available Spots on current board  
    availableSpots = possibilities(board)
    #Check if location is in the available spots list
    if (possibilities(create_board())[location] in availableSpots):
        #if so, update board 
        board[possibilities(create_board())[location]] = player
        #return board
        return(board)
    #Else, return none
    else:
      return(None)
        

In [ ]:
board = create_board()
player_turn(board, 1, 4)
player_turn(board, 1, 4)


In [ ]:
#function to take user input
def numInput():
  #prompt for user input
  num = input("Enter a number between 0 and 8: ")
  #if number is digit and between 0 and 8
  if num.isdigit() and int(num) >= 0 and int(num) <= 8:
      #return input
      return(num)
  #else re-run function
  else:
    print("Invail input. ")
    numInput()
    

In [ ]:
#Test numInput
numInput()

Enter a number between 0 and 8: 3


'3'

In [ ]:
# Checks whether the player has three  
# of their marks in a horizontal row 
def row_win(board, player): 
    for x in range(len(board)): 
        win = True
          
        for y in range(len(board)): 
            if board[x, y] != player: 
                win = False
                continue
                
        if win == True: 
            return(win) 
    return(win) 

In [ ]:
# Checks whether the player has three 
# of their marks in a vertical row 
def col_win(board, player): 
   #similar logic to row_win
    for x in range(len(board)): 
        win = True
          
        for y in range(len(board)): 
            if board[x, y] != player: 
                win = False
                continue
                
        if win == True: 
            return(win) 
    return(win) 

In [ ]:
# Checks whether the player has three 
# of their marks in a diagonal row 
def diag_win(board, player): 
    #similar logic to row_win
    win = True
    
    for x in range(len(board)):
      if board[x,x] != player:
        win = False
    return(win)

In [ ]:
# Evaluates whether there is 
# a winner or a tie  
def evaluate(board):
    winner = 0
      
    for player in [1, 2]: 
        if (row_win(board, player) or
            col_win(board,player) or 
            diag_win(board,player)): 
                 
            winner = player 
              
    if np.all(board != 0) and winner == 0: 
        winner = -1
    return winner 

In [ ]:
#Play game with computer, 1, or 2 players. 
def play_game(numberOfPlayers = 0): 
    #create board
    board = create_board()
    #set winner to 0
    winner = 0
    #initialize counter to 1
    counter = 1
    
    boardMapLocation = boardMap()
    #print out initial board
    print(board)
    #Pause game for 2 
    sleep(2)
    
    #Loop until there is a winner
    while winner == 0: 
        #For each player - [1,2]
        for player in [1, 2]: 
            #If number of players equals 1 and it's player 1's turn, or if there are 2 players
            if (numberOfPlayers == 1 & player == 1) | (numberOfPlayers == 2):
              #print out the locations
              print("Turn locations:")
              print(boardMapLocation)
              print("Player" + str(player) + "'s turn.")
              #prompt for user input
              playerTurn = numInput()
              #call player turn function and update board
              board = player_turn(board, player, playerTurn) 
              #While board was not updated - board is none
              while board is None:
                print("Please select a valid location.")
                playerTurn = numInput()
                board = player_turn(board, player, playerTurn) 
            else:
              print("Computer player" + str(player) + "'s turn.")
              board = random_place(board, player)
            print("Board after " + str(counter) + " move") 
            print(board) 
            sleep(2) 
            counter += 1
            winner = evaluate(board) 
            if winner != 0: 
                break
    return(winner) 

In [ ]:
# Play game and print out the winner
print("Winner is player " + str(play_game(1))) 

[[0 0 0]
 [0 0 0]
 [0 0 0]]
Turn locations:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Player1's turn.
Enter a number between 0 and 8: 4


TypeError: ignored